key_config:
  +joint0 : 'd'  
  -joint0 : 'a'
  +joint1 : 'w'
  -joint1 : 's'
  +joint2 : 'r'
  -joint2 : 'f'
  +joint3 : '4'
  -joint3 : '6'
  +joint4 : '8'
  -joint4 : '2'
  +joint5 : '9'
  -joint5 : '7'
  reset : '='
  quit : '-'

velocity_param: #target_vel
  joint0_velocity: 1  
  joint1_velocity: 1  
  joint2_velocity: 1  
  joint3_velocity: 1
  joint4_velocity: 1  
  joint5_velocity: 1

increment_param:
  joint0_increment: 0.05  #(-0.65,0.65)
  joint1_increment: 0.07  #(-3.14,3.14)
  joint2_increment: 0.07  #(-3.14,3.14)
  joint3_increment: 0.07  #(-3.14,3.14)
  joint4_increment: 0.07  #(-3.14,3.14)
  joint5_increment: 0.07  #(-3.14,3.14)
  joint6_increment: 0.07  #(-3.14,3.14)
