q: +joint0_position
a: -joint0_position
w: +joint1_position
s: -joint1_position
e: +joint2_position
d: -joint2_position
r: +joint3_position
f: -joint3_position
t: +joint4_position
g: -joint4_position
y: +joint5_position
h: -joint5_position
u: +joint6_position
j: -joint6_position
1: 0.02
2: 0.05
3: 0.12
k: reset_positions
x: quit
